version: "3.3"
services:
  sut:
    build: ./test/smoke/
    links:
      - app
  app:
    image: bkimminich/juice-shop:latest-amd64
    build: ./
 
 secrets:
   api_token: c6a40151a76a5f86887585xxxa55cf55
 
